# Generated by Django 6.0.2 on 2026-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Physics', 'Physics'), ('Camestry', 'Camestry'), ('ICT', 'ICT')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Teacher', 'Teacher'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Student', 'Student')], default='student', max_length=20),
        ),
    ]
