# Generated by Django 6.0.2 on 2026-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_studentattendance_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='cgpa',
            new_name='total_attendance_count',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='subject',
            new_name='total_class_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Accounts', 'Accounts')], default='student', max_length=20),
        ),
    ]
