# Generated by Django 6.0.2 on 2026-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_subject_subject_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin'), ('Accounts', 'Accounts'), ('Manager', 'Manager')], default='student', max_length=20),
        ),
    ]
